server:
  port: 8082

spring:
  application:
    name: CROP-ORDER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/cropdeal_user_db
    username: root
    password: Dell@7400
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  cloud:
    config:
      uri: http://localhost:8888
      name: crop-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
